#!/bin/bash

########### Удаление пакетов

function checkerror {
		if [ $1 != "y" && $1 != "Y" && $1 != "n" && $1 != "N" ]
		then
				read -p $'\033[1;33m = = = = Please, enter [y] or [n]: \033[m' $1
				checkerrorerror $1
		fi
}

while true
do
        read -p $'\033[37m = = = = Do you want to remove Git [y/n]? \033[m' gitchoice 
        checkerror gitchoice
        read -p $'\033[1;33m = = = = Are you sure [y/n]?' gitconfirm
        checkerror gitconfirm

        if [ $gitconfirm == 'n' || $gitconfirm == 'N' ]
        then
                continue
        elif [ $gitchoice == 'y' || $gitchoice == 'Y' ]
        then
                sudo apt-get purge git -y

                if [ $? -ne 0 ]
                then
                        echo -e '\033[91m = = = = Git has NOT been purged. Please, solve all issues and try to remove package again = = = = \033[m'
                else
                        echo -e '\033[92m = = = = Git has been successfully purged = = = = \033[m'
                fi

                break
        elif [ $gitchoice == 'n' $gitchoice == 'n']
                echo -e '\033[37m = = = = Skipping ... = = = = \033[m'
                break
        fi
done

while true
do
        read -p $'\033[37m = = = = Do you want to remove Node Exporter [y/n]? \033[m' nodechoice
        checkerror nodechoice
        read -p $'\033[33m = = = = Are you sure [y/n]?' nodeconfirm
        checkerror nodeconfirm

        if [ $nodeconfirm == 'n' || $nodeconfirm == 'N' ]
        then
                continue
        elif [ $nodechoice == 'y' || $nodechoice == 'Y' ]
        then
                sudo apt-get purge prometheus-node-exporter -y
				sudo rm -dr /etc/node-exporter/
                if [ $? -ne 0 ]
                then
                        echo -e '\033[91m = = = = Node Exporter has NOT been purged. Please, solve all issues and try to remove package again = = = = \033[m'
                else
                        echo -e '\033[92m = = = = Node Exporter has been successfully purged = = = = \033[m'
                fi

                break
        elif [ $nodechoice == 'n' || $nodechoice == 'N' ]
                echo -e '\033[37m = = = = Skipping ... = = = = \033[m'
				sudo sed -i 's| --web.config.file="/etc/node-exporter/config.yml"||' /usr/lib/systemd/system/prometheus-node-exporter.service
				sudo systemctl daemon-reload
				sudo systemctl restart prometheus-node-exporter
                break
        fi
done

while true
do
        read -p $'\033[37m = = = = Do you want to remove "apache2-utils" package [y/n]? \033[m' gitchoice 
        checkerror gitchoice
        read -p $'\033[1;33m = = = = Are you sure [y/n]?' gitconfirm
        checkerror gitconfirm

        if [ $gitconfirm == 'n' || $gitconfirm == 'N' ]
        then
                continue
        elif [ $gitchoice == 'y' || $gitchoice == 'Y' ]
        then
                sudo apt-get purge apache2-utils -y

                if [ $? -ne 0 ]
                then
                        echo -e '\033[91m = = = = "apache2-utils" package has NOT been purged. Please, solve all issues and try to remove package again = = = = \033[m'
                else
                        echo -e '\033[92m = = = = "apache2-utils" package has been successfully purged = = = = \033[m'
                fi

                break
        elif [ $gitchoice == 'n' $gitchoice == 'n']
                echo -e '\033[37m = = = = Skipping ... = = = = \033[m'
                break
        fi
done

########### Откат настроек фаерволла

promip=`cat /tmp/promip.is`

sudo iptables -D INPUT -i lo -j ACCEPT
sudo iptables -D INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
sudo iptables -D INPUT -p tcp --dport 80 -j ACCEPT
sudo iptables -D INPUT -p tcp --dport 443 -j ACCEPT
sudo iptables -D INPUT -p tcp --dport 22 -j ACCEPT
sudo iptables -D INPUT -p tcp --dport 21 -j ACCEPT
sudo iptables -D INPUT -p tcp -s $promip --dport 9100 -j ACCEPT

sudo iptables -P INPUT ACCEPT
sudo iptables -P FORWARD ACCEPT
sudo iptables -P OUTPUT ACCEPT

sudo service netfilter-persistent save

echo -e '\033[92m = = = = Firewall rules have been rolled back = = = = \033[m'

########### Отключение юнитов и возврат файлов пакета

sudo systemctl stop auto-backup.service
sudo systemctl disable auto-backup.service
sudo systemctl stop auto-backup.timer
sudo systemctl disable auto-backup.service

echo -e '\033[92m = = = = "auto-backup" systemd-units have been successfully disabled  = = = = \033[m'

sudo mv /etc/systemd/system/auto-backup.service /tmp
sudo mv /etc/systemd/system/auto-backup.timer /tmp
sudo mv /usr/local/bin/auto-backup.sh /tmp
sudo mv /home/$USER/vpn-setup-scripts /tmp

########### Откат настроек node-экспортера

echo -e '\033[92m = = = = Systemd-unit changes have been rolled back successfully  = = = = \033[m'
