#!/bin/bash

sudo sed -i '/^  - "ovpn.yml"/d' /etc/prometheus.yml
sudo sed -i '/Alerting in Telegram TelepushBot/,/Alerting in Telegram TelepushBot/d' /etc/prometheus/alertmanager.yml

function checkerror {
		if [ $1 != "y" && $1 != "Y" && $1 != "n" && $1 != "N" ]
		then
				read -p $'\033[37m = = = = Please, enter [y] or [n]: \033[m' $1
				error $1
		fi
}

while true
do
        read -p $'\033[37m = = = = Do you want to remove Git [y/n]? \033[m' gitchoice 
        checkerror gitchoice
        read -p $'\033[33m = = = = Are you sure [y/n]?' gitconfirm
        checkerror gitconfirm

        if [ $gitconfirm == 'n' || $gitconfirm == 'N' ]
        then
                continue
        elif [ $gitchoice == 'y' || $gitchoice == 'Y' ]
        then
                sudo apt-get purge git

                if [ $? -ne 0 ]
                then
                        echo -e '\033[91m = = = = Git has NOT been purged. Please, solve all issues and try to remove package again = = = = \033[m'
                else
                        echo -e '\033[92m = = = = Git has been successfully purged = = = = \033[m'
                fi

                break
        elif [ $gitchoice == 'n' $gitchoice == 'n']
                echo -e '\033[37m = = = = Skipping ... = = = = \033[m'
                break
        fi
done

while true
do
        read -p $'\033[37m = = = = Do you want to remove Prometheus [y/n]? \033[m' promchoice
        checkerror promchoice
        read -p $'\033[33m = = = = Are you sure [y/n]?' promconfirm
        checkerror promconfirm

        if [ $promconfirm == 'n' || $promconfirm == 'N' ]
        then
                continue
        elif [ $promchoice == 'y' || $promchoice == 'Y' ]
        then
                sudo apt-get purge prometheus

                if [ $? -ne 0 ]
                then
                        echo -e '\033[91m = = = = Prometheus has NOT been purged. Please, solve all issues and try to remove package again = = = = \033[m'
                else
                        echo -e '\033[92m = = = = Prometheus has been successfully purged = = = = \033[m'
                fi

                break
        elif [ $promchoice == 'n' || $promchoice == 'N' ]
                echo -e '\033[37m = = = = Skipping ... = = = = \033[m'
                break
        fi
done

while true
do
        read -p $'\033[37m = = = = Do you want to remove Alertmanager [y/n]? \033[m' alertchoice
        checkerror alertchoice
        read -p $'\033[33m = = = = Are you sure [y/n]?' alertconfirm
        checkerror alertconfirm

        if [ $alertconfirm == 'n' || $alertconfirm == 'N' ]
        then
                continue
        elif [ $alertchoice == 'y' || $alertchoice == 'n' ]
        then
                sudo apt-get purge prometheus-alertmanager

                if [ $? -ne 0 ]
                then
                        echo -e '\033[91m = = = = Alertmanager has NOT been purged. Please, solve all issues and try to remove package again = = = = \033[m'
                else
                        echo -e '\033[92m = = = = Alertmanager has been successfully purged = = = = \033[m'
                fi

                break
        elif [ $alertchoice == 'n' || $alertchoice == 'n' ]
                sudo chown $USER:$USER /etc/prometheus/alertmanager.yml
                sed -i '' /etc/prometheus/alertmanager.yml 
                sudo chown root:root /etc/prometheus/alertmanager.yml
                echo -e '\033[37m = = = = Skipping ... = = = = \033[m'
                break
        fi
done

while true
do
        read -p $'\033[37m = = = = Do you want to remove Node Exporter [y/n]? \033[m' nodechoice
        checkerror nodechoice
        read -p $'\033[33m = = = = Are you sure [y/n]?' nodeconfirm
        checkerror nodeconfirm

        if [ $nodeconfirm == 'n' || $nodeconfirm == 'N' ]
        then
                continue
        elif [ $nodechoice == 'y' || $nodechoice == 'Y' ]
        then
                sudo apt-get purge prometheus-node-exporter

                if [ $? -ne 0 ]
                then
                        echo -e '\033[91m = = = = Node Exporter has NOT been purged. Please, solve all issues and try to remove package again = = = = \033[m'
                else
                        echo -e '\033[92m = = = = Node Exporter has been successfully purged = = = = \033[m'
                fi

                break
        elif [ $nodechoice == 'n' || $nodechoice == 'N' ]
                echo -e '\033[37m = = = = Skipping ... = = = = \033[m'
                break
        fi
done

sudo systemctl stop auto-backup.service
sudo systemctl disable auto-backup.service
sudo systemctl stop auto-backup.timer
sudo systemctl disable auto-backup.service

echo -e '\033[92m = = = = "ovpn-up" and "auto-backup" systemd-units have been successfully disabled  = = = = '

sudo mv /etc/prometheus/ovpn.yml /tmp
sudo mv /etc/systemd/system/auto-backup.service /tmp
sudo mv /etc/systemd/system/auto-backup.timer /tmp
sudo mv /usr/local/bin/auto-backup.sh /tmp
sudo mv /home/$USER/vpn-setup-scripts /tmp
